server.port: 8081

spring:
  datasource:
    platform: postgres
    url: jdbc:postgresql://localhost:5432/academia
    username: postgres
    password: postgres

  jpa:
    show-sql: true
    generate-dll: true
    hibernate:
      dll-auto: update
    proprieties:
      hibernate.format_sql: true

  logging:
    level:
      org:
        hibernate:
          type: trace
