
spring:
  datasource:
    dbcp2:
      driver-class-name: org.postgresql.Driver
    platform: postgres
    url: jdbc:postgresql://localhost:5432/academia?useTimezone=true&serverTimezone=UTC&useLegacyData
    username: postgres
    password: postgres

  jpa:
    show-sql: true
    generate-dll: true
    hibernate:
      dll-auto: update
    proprieties:
      hibernate.format_sql: true

  logging:
    level:
      org:
        hibernate:
          type: trace
